import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/userShared/Navbar/Navbar";
import Footer from "@/components/userShared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wedding",
  description: "Generated by <Tamzid/>",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
