import { Merriweather } from "next/font/google" ;
import "./globals.css";
import Navbar from "@/components/userShared/Navbar/Navbar";
import Footer from "@/components/userShared/Footer/Footer";


const merriweather = Merriweather({
  weight: '400',
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Wedding",
  description: "Generated by <Tamzid/>",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
      <Navbar/>
        {children}
      <Footer/>
        </body>
    </html>
  );
}
