import { Merriweather } from "next/font/google" ;
import "./globals.css";

import UserLayout from "@/components/userShared/UserLayout/page";

const merriweather = Merriweather({
  weight: '400',
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

export const metadata = {
  title: "Wedding",
  description: "Generated by <Tamzid/>",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={merriweather.className}>
        <UserLayout>
          { children }
          </UserLayout>
      </body>
    </html>
  );
}
